name: Playwright Tests
on:
  push:
jobs:
  test:
    timeout-minutes: 30
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Install dependencies
        run: |
          npm run update:axonivy:next
          npm install
          npm run build:production
          npm run download:engine https://dev.axonivy.com/permalink/dev/axonivy-engine.zip
          rmdir extension/AxonIvyEngine/system/demo-applications
      - name: Run Playwright tests
        run: |
          start extension/AxonIvyEngine/bin/AxonIvyEngine.exe
          npm run test:playwright:download:vscode
          npm run test:playwright
        env:
          CI: true
          RUN_STABLE_VERSION: true
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: archive
          path: |
            playwright/playwright-videos/
            extension/AxonIvyEngine/logs
          retention-days: 10
# name: Playwright Tests
# on:
#   push:
# jobs:
#   test:
#     env:
#       IVY_JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/21.0.3-9.0.LTS/x64
#     timeout-minutes: 30
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 22
#       - uses: actions/setup-java@v4
#         with:
#           java-version: '21.0.3'
#           distribution: 'temurin'
#       - name: Install dependencies
#         run: |
#           echo $IVY_JAVA_HOME
#           npm run update:axonivy:next
#           npm install
#           npm run build:production
#           npm run download:engine https://download.axonivy.com/dev/AxonIvyEngine13.1.0.2502141306_All_x64.zip
#       - name: Run Playwright tests
#         run: |
#           java --version
#           nohup extension/AxonIvyEngine/bin/AxonIvyEngine &
#           npm run test:playwright:download:vscode
#           xvfb-run --auto-servernum npm run test:playwright
#       - uses: actions/upload-artifact@v4
#         if: ${{ !cancelled() }}
#         with:
#           name: playwright-videos
#           path: playwright/playwright-videos/
#           retention-days: 3
