name: Playwright Tests
on:
  push:
jobs:
  test:
    timeout-minutes: 30
    runs-on: macos-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install dependencies
        run: |
          node --version
          echo $CI
          npm run update:axonivy:next
          npm install
          npm run build:production
          npm run download:engine https://download.axonivy.com/dev/AxonIvyEngine13.1.0.2502121306_All_x64.zip
          node --version
      - name: Run Playwright tests
        run: |
          nohup extension/AxonIvyEngine/bin/AxonIvyEngine &
          npm run test:playwright:download:vscode
          npm run test:playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-videos
          path: playwright/playwright-videos/
          retention-days: 3
