name: Playwright Tests
on:
  push:
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Install dependencies
        run: |
          npm run update:axonivy:next
          npm install
          npm run build:production
          npm run download:engine https://download.axonivy.com/dev/AxonIvyEngine13.1.0.2502141306_All_x64.zip
      - name: Run Playwright tests
        run: |
          extension/AxonIvyEngine/bin/AxonIvyEngine startdaemon
          npm run test:playwright:download:vscode
          xvfb-run --auto-servernum npm run test:playwright
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-videos
          path: playwright/playwright-videos/
          retention-days: 3
